/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _ImmutableObjectStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _ImmutableObjectStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const TokenTransaction = IDL.Record({
  'id' : IDL.Nat,
  'to' : IDL.Opt(IDL.Principal),
  'status' : IDL.Text,
  'transactionType' : IDL.Text,
  'from' : IDL.Opt(IDL.Principal),
  'pool' : IDL.Opt(IDL.Text),
  'reference' : IDL.Opt(IDL.Text),
  'timestamp' : IDL.Int,
  'amount' : IDL.Nat,
  'ledgerHeight' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Player = IDL.Record({
  'gamesPlayed' : IDL.Nat,
  'scores' : IDL.Vec(IDL.Nat),
  'name' : IDL.Text,
  'highestScore' : IDL.Nat,
  'totalSpares' : IDL.Nat,
  'totalStrikes' : IDL.Nat,
  'totalPoints' : IDL.Nat,
  'averageScore' : IDL.Nat,
});
export const Frame = IDL.Record({
  'score' : IDL.Nat,
  'roll1' : IDL.Nat,
  'roll2' : IDL.Nat,
  'roll3' : IDL.Opt(IDL.Nat),
});
export const Game = IDL.Record({
  'id' : IDL.Nat,
  'totalScores' : IDL.Vec(IDL.Nat),
  'owner' : IDL.Opt(IDL.Principal),
  'players' : IDL.Vec(Player),
  'timestamp' : IDL.Int,
  'frames' : IDL.Vec(IDL.Vec(Frame)),
});
export const ChatMessage = IDL.Record({
  'gameId' : IDL.Nat,
  'sender' : IDL.Text,
  'message' : IDL.Text,
  'timestamp' : IDL.Int,
});
export const Team = IDL.Record({
  'id' : IDL.Nat,
  'creator' : IDL.Principal,
  'members' : IDL.Vec(IDL.Principal),
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'description' : IDL.Text,
  'bestScore' : IDL.Nat,
  'totalGames' : IDL.Nat,
  'averageScore' : IDL.Nat,
});
export const UserProfile = IDL.Record({
  'principal' : IDL.Principal,
  'displayName' : IDL.Text,
  'gamesPlayed' : IDL.Nat,
  'highestScore' : IDL.Nat,
  'totalSpares' : IDL.Nat,
  'achievements' : IDL.Vec(IDL.Text),
  'games' : IDL.Vec(IDL.Nat),
  'totalStrikes' : IDL.Nat,
  'totalPoints' : IDL.Nat,
  'profilePicture' : IDL.Opt(IDL.Text),
  'averageScore' : IDL.Nat,
});
export const Wallet = IDL.Record({
  'stkPrincipalId' : IDL.Text,
  'icpTransactions' : IDL.Vec(TokenTransaction),
  'icpAccountId' : IDL.Text,
  'stkBalance' : IDL.Nat,
  'stkTransactions' : IDL.Vec(TokenTransaction),
});
export const FileReference = IDL.Record({
  'hash' : IDL.Text,
  'path' : IDL.Text,
});
export const Invitation = IDL.Record({
  'invitee' : IDL.Principal,
  'inviter' : IDL.Principal,
  'timestamp' : IDL.Int,
  'teamId' : IDL.Nat,
});
export const JoinRequest = IDL.Record({
  'requester' : IDL.Principal,
  'timestamp' : IDL.Int,
  'teamId' : IDL.Nat,
});
export const PaymentTransaction = IDL.Record({
  'id' : IDL.Nat,
  'status' : IDL.Text,
  'stkAmount' : IDL.Nat,
  'user' : IDL.Principal,
  'reference' : IDL.Opt(IDL.Text),
  'exchangeRate' : IDL.Nat,
  'timestamp' : IDL.Int,
  'icpAmount' : IDL.Nat,
});
export const PriceFeed = IDL.Record({
  'status' : IDL.Text,
  'source' : IDL.Text,
  'icpUsd' : IDL.Nat,
  'lastUpdated' : IDL.Int,
});
export const TokenPool = IDL.Record({
  'total' : IDL.Nat,
  'name' : IDL.Text,
  'remaining' : IDL.Nat,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  '_immutableObjectStorageBlobsAreLive' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [IDL.Vec(IDL.Bool)],
      ['query'],
    ),
  '_immutableObjectStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_immutableObjectStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_ImmutableObjectStorageCreateCertificateResult],
      [],
    ),
  '_immutableObjectStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
      [_ImmutableObjectStorageRefillResult],
      [],
    ),
  '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControl' : IDL.Func([], [], []),
  'acceptInvitation' : IDL.Func([IDL.Nat], [], []),
  'addIcpTransaction' : IDL.Func(
      [TokenTransaction],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'addStkTransaction' : IDL.Func(
      [TokenTransaction],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'adjustPoolAllocation' : IDL.Func(
      [IDL.Text, IDL.Nat],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'approveJoinRequest' : IDL.Func([IDL.Nat, IDL.Principal], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createTeam' : IDL.Func([IDL.Text, IDL.Text], [IDL.Nat], []),
  'creditUserWallet' : IDL.Func([IDL.Principal, IDL.Nat], [], []),
  'declineInvitation' : IDL.Func([IDL.Nat], [], []),
  'denyJoinRequest' : IDL.Func([IDL.Nat, IDL.Principal], [], []),
  'dropFileReference' : IDL.Func([IDL.Text], [], []),
  'fetchIcpPrice' : IDL.Func([IDL.Text], [IDL.Text], []),
  'getAdminAuditTrail' : IDL.Func(
      [],
      [IDL.Variant({ 'ok' : IDL.Vec(TokenTransaction), 'err' : IDL.Text })],
      ['query'],
    ),
  'getAdminIcpWallet' : IDL.Func([], [IDL.Opt(IDL.Text)], ['query']),
  'getAdminTreasuryAddress' : IDL.Func([], [IDL.Opt(IDL.Text)], ['query']),
  'getAllGames' : IDL.Func([], [IDL.Vec(Game)], ['query']),
  'getAllMessages' : IDL.Func([], [IDL.Vec(ChatMessage)], ['query']),
  'getAllPlayerStats' : IDL.Func([], [IDL.Vec(Player)], ['query']),
  'getAllTeams' : IDL.Func([], [IDL.Vec(Team)], ['query']),
  'getAllUserProfiles' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
  'getCallerAccountIds' : IDL.Func([], [IDL.Text, IDL.Text], ['query']),
  'getCallerAddresses' : IDL.Func([], [IDL.Text, IDL.Text], ['query']),
  'getCallerDerivedAccountId' : IDL.Func([], [IDL.Text], ['query']),
  'getCallerIcpBalance' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Nat, 'err' : IDL.Text })],
      [],
    ),
  'getCallerIcpTransactions' : IDL.Func(
      [],
      [IDL.Vec(TokenTransaction)],
      ['query'],
    ),
  'getCallerPrincipalId' : IDL.Func([], [IDL.Text], ['query']),
  'getCallerStkBalance' : IDL.Func([], [IDL.Nat], ['query']),
  'getCallerStkTransactions' : IDL.Func(
      [],
      [IDL.Vec(TokenTransaction)],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCallerWallet' : IDL.Func([], [IDL.Opt(Wallet)], ['query']),
  'getCallerWalletSummary' : IDL.Func(
      [],
      [
        IDL.Nat,
        IDL.Vec(TokenTransaction),
        IDL.Vec(TokenTransaction),
        IDL.Text,
        IDL.Text,
      ],
      ['query'],
    ),
  'getFileReference' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(FileReference)],
      ['query'],
    ),
  'getGame' : IDL.Func([IDL.Nat], [IDL.Opt(Game)], ['query']),
  'getInvitations' : IDL.Func([], [IDL.Vec(Invitation)], ['query']),
  'getJoinRequests' : IDL.Func([], [IDL.Vec(JoinRequest)], ['query']),
  'getLeaderboard' : IDL.Func([], [IDL.Vec(Player)], ['query']),
  'getLedgerPrincipal' : IDL.Func(
      [],
      [IDL.Variant({ 'ok' : IDL.Principal, 'err' : IDL.Text })],
      ['query'],
    ),
  'getMessages' : IDL.Func([IDL.Nat], [IDL.Vec(ChatMessage)], ['query']),
  'getPaymentTransaction' : IDL.Func(
      [IDL.Nat],
      [IDL.Opt(PaymentTransaction)],
      [],
    ),
  'getPaymentTransactions' : IDL.Func([], [IDL.Vec(PaymentTransaction)], []),
  'getPlayerStats' : IDL.Func([IDL.Text], [IDL.Opt(Player)], ['query']),
  'getPoolManagementHistory' : IDL.Func(
      [],
      [IDL.Variant({ 'ok' : IDL.Vec(TokenTransaction), 'err' : IDL.Text })],
      ['query'],
    ),
  'getPriceFeed' : IDL.Func([IDL.Text], [IDL.Opt(PriceFeed)], []),
  'getPriceFeeds' : IDL.Func([], [IDL.Vec(PriceFeed)], []),
  'getRealTimePoolBalances' : IDL.Func(
      [],
      [IDL.Variant({ 'ok' : IDL.Vec(TokenPool), 'err' : IDL.Text })],
      ['query'],
    ),
  'getTeam' : IDL.Func([IDL.Nat], [IDL.Opt(Team)], ['query']),
  'getTokenPool' : IDL.Func([IDL.Text], [IDL.Opt(TokenPool)], []),
  'getTokenPools' : IDL.Func([], [IDL.Vec(TokenPool)], []),
  'getTokenTransaction' : IDL.Func([IDL.Nat], [IDL.Opt(TokenTransaction)], []),
  'getTokenTransactions' : IDL.Func([], [IDL.Vec(TokenTransaction)], []),
  'getTotalSupply' : IDL.Func([], [IDL.Nat], []),
  'getTotalSupplyStatus' : IDL.Func(
      [],
      [IDL.Variant({ 'ok' : IDL.Nat, 'err' : IDL.Text })],
      ['query'],
    ),
  'getUserBalance' : IDL.Func([IDL.Principal], [IDL.Nat], []),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getWallet' : IDL.Func([IDL.Principal], [IDL.Opt(Wallet)], ['query']),
  'initializeAccessControl' : IDL.Func([], [], []),
  'initializeWallet' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'inviteToTeam' : IDL.Func([IDL.Nat, IDL.Principal], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'leaveTeam' : IDL.Func([IDL.Nat], [], []),
  'listFileReferences' : IDL.Func([], [IDL.Vec(FileReference)], ['query']),
  'loginUser' : IDL.Func(
      [],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'mintStkTokens' : IDL.Func(
      [IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'receiveStkTokens' : IDL.Func(
      [IDL.Nat],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'recomputeMyAccountId' : IDL.Func(
      [],
      [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
      [],
    ),
  'recordIcpSend' : IDL.Func(
      [IDL.Text, IDL.Nat, IDL.Nat],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'recordPaymentTransaction' : IDL.Func(
      [IDL.Principal, IDL.Nat, IDL.Nat, IDL.Text, IDL.Opt(IDL.Text)],
      [IDL.Nat],
      [],
    ),
  'recordTokenTransaction' : IDL.Func(
      [
        IDL.Opt(IDL.Principal),
        IDL.Opt(IDL.Principal),
        IDL.Nat,
        IDL.Text,
        IDL.Opt(IDL.Text),
        IDL.Text,
        IDL.Opt(IDL.Text),
      ],
      [IDL.Nat],
      [],
    ),
  'registerFileReference' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'requestToJoinTeam' : IDL.Func([IDL.Nat], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'saveGame' : IDL.Func(
      [
        IDL.Vec(Player),
        IDL.Vec(IDL.Vec(Frame)),
        IDL.Vec(IDL.Nat),
        IDL.Opt(IDL.Principal),
      ],
      [IDL.Nat],
      [],
    ),
  'sendMessage' : IDL.Func([IDL.Text, IDL.Text, IDL.Nat], [], []),
  'sendStkTokens' : IDL.Func(
      [IDL.Text, IDL.Nat],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'setAdminIcpWallet' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'setAdminTreasuryAccount' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'setLedgerPrincipal' : IDL.Func(
      [IDL.Principal],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'transferTokensBetweenPools' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Nat],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'updateCallerAchievements' : IDL.Func([IDL.Vec(IDL.Text)], [], []),
  'updateCallerProfilePicture' : IDL.Func([IDL.Text], [], []),
  'updateCallerUserProfileStats' : IDL.Func(
      [IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat],
      [],
      [],
    ),
  'updateCallerWallet' : IDL.Func(
      [IDL.Nat],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'updatePlayerStats' : IDL.Func(
      [IDL.Text, IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat],
      [],
      [],
    ),
  'updatePriceFeed' : IDL.Func([IDL.Text, IDL.Nat, IDL.Text], [], []),
  'updateTeamStats' : IDL.Func([IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat], [], []),
  'updateTokenPool' : IDL.Func([IDL.Text, IDL.Nat], [], []),
  'updateTotalSupply' : IDL.Func([IDL.Nat], [], []),
  'updateUserBalance' : IDL.Func([IDL.Principal, IDL.Nat], [], []),
  'verifyIcpPayment' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Nat, 'err' : IDL.Text })],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _ImmutableObjectStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _ImmutableObjectStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const TokenTransaction = IDL.Record({
    'id' : IDL.Nat,
    'to' : IDL.Opt(IDL.Principal),
    'status' : IDL.Text,
    'transactionType' : IDL.Text,
    'from' : IDL.Opt(IDL.Principal),
    'pool' : IDL.Opt(IDL.Text),
    'reference' : IDL.Opt(IDL.Text),
    'timestamp' : IDL.Int,
    'amount' : IDL.Nat,
    'ledgerHeight' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Player = IDL.Record({
    'gamesPlayed' : IDL.Nat,
    'scores' : IDL.Vec(IDL.Nat),
    'name' : IDL.Text,
    'highestScore' : IDL.Nat,
    'totalSpares' : IDL.Nat,
    'totalStrikes' : IDL.Nat,
    'totalPoints' : IDL.Nat,
    'averageScore' : IDL.Nat,
  });
  const Frame = IDL.Record({
    'score' : IDL.Nat,
    'roll1' : IDL.Nat,
    'roll2' : IDL.Nat,
    'roll3' : IDL.Opt(IDL.Nat),
  });
  const Game = IDL.Record({
    'id' : IDL.Nat,
    'totalScores' : IDL.Vec(IDL.Nat),
    'owner' : IDL.Opt(IDL.Principal),
    'players' : IDL.Vec(Player),
    'timestamp' : IDL.Int,
    'frames' : IDL.Vec(IDL.Vec(Frame)),
  });
  const ChatMessage = IDL.Record({
    'gameId' : IDL.Nat,
    'sender' : IDL.Text,
    'message' : IDL.Text,
    'timestamp' : IDL.Int,
  });
  const Team = IDL.Record({
    'id' : IDL.Nat,
    'creator' : IDL.Principal,
    'members' : IDL.Vec(IDL.Principal),
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'description' : IDL.Text,
    'bestScore' : IDL.Nat,
    'totalGames' : IDL.Nat,
    'averageScore' : IDL.Nat,
  });
  const UserProfile = IDL.Record({
    'principal' : IDL.Principal,
    'displayName' : IDL.Text,
    'gamesPlayed' : IDL.Nat,
    'highestScore' : IDL.Nat,
    'totalSpares' : IDL.Nat,
    'achievements' : IDL.Vec(IDL.Text),
    'games' : IDL.Vec(IDL.Nat),
    'totalStrikes' : IDL.Nat,
    'totalPoints' : IDL.Nat,
    'profilePicture' : IDL.Opt(IDL.Text),
    'averageScore' : IDL.Nat,
  });
  const Wallet = IDL.Record({
    'stkPrincipalId' : IDL.Text,
    'icpTransactions' : IDL.Vec(TokenTransaction),
    'icpAccountId' : IDL.Text,
    'stkBalance' : IDL.Nat,
    'stkTransactions' : IDL.Vec(TokenTransaction),
  });
  const FileReference = IDL.Record({ 'hash' : IDL.Text, 'path' : IDL.Text });
  const Invitation = IDL.Record({
    'invitee' : IDL.Principal,
    'inviter' : IDL.Principal,
    'timestamp' : IDL.Int,
    'teamId' : IDL.Nat,
  });
  const JoinRequest = IDL.Record({
    'requester' : IDL.Principal,
    'timestamp' : IDL.Int,
    'teamId' : IDL.Nat,
  });
  const PaymentTransaction = IDL.Record({
    'id' : IDL.Nat,
    'status' : IDL.Text,
    'stkAmount' : IDL.Nat,
    'user' : IDL.Principal,
    'reference' : IDL.Opt(IDL.Text),
    'exchangeRate' : IDL.Nat,
    'timestamp' : IDL.Int,
    'icpAmount' : IDL.Nat,
  });
  const PriceFeed = IDL.Record({
    'status' : IDL.Text,
    'source' : IDL.Text,
    'icpUsd' : IDL.Nat,
    'lastUpdated' : IDL.Int,
  });
  const TokenPool = IDL.Record({
    'total' : IDL.Nat,
    'name' : IDL.Text,
    'remaining' : IDL.Nat,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    '_immutableObjectStorageBlobsAreLive' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [IDL.Vec(IDL.Bool)],
        ['query'],
      ),
    '_immutableObjectStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_immutableObjectStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_ImmutableObjectStorageCreateCertificateResult],
        [],
      ),
    '_immutableObjectStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
        [_ImmutableObjectStorageRefillResult],
        [],
      ),
    '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControl' : IDL.Func([], [], []),
    'acceptInvitation' : IDL.Func([IDL.Nat], [], []),
    'addIcpTransaction' : IDL.Func(
        [TokenTransaction],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'addStkTransaction' : IDL.Func(
        [TokenTransaction],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'adjustPoolAllocation' : IDL.Func(
        [IDL.Text, IDL.Nat],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'approveJoinRequest' : IDL.Func([IDL.Nat, IDL.Principal], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createTeam' : IDL.Func([IDL.Text, IDL.Text], [IDL.Nat], []),
    'creditUserWallet' : IDL.Func([IDL.Principal, IDL.Nat], [], []),
    'declineInvitation' : IDL.Func([IDL.Nat], [], []),
    'denyJoinRequest' : IDL.Func([IDL.Nat, IDL.Principal], [], []),
    'dropFileReference' : IDL.Func([IDL.Text], [], []),
    'fetchIcpPrice' : IDL.Func([IDL.Text], [IDL.Text], []),
    'getAdminAuditTrail' : IDL.Func(
        [],
        [IDL.Variant({ 'ok' : IDL.Vec(TokenTransaction), 'err' : IDL.Text })],
        ['query'],
      ),
    'getAdminIcpWallet' : IDL.Func([], [IDL.Opt(IDL.Text)], ['query']),
    'getAdminTreasuryAddress' : IDL.Func([], [IDL.Opt(IDL.Text)], ['query']),
    'getAllGames' : IDL.Func([], [IDL.Vec(Game)], ['query']),
    'getAllMessages' : IDL.Func([], [IDL.Vec(ChatMessage)], ['query']),
    'getAllPlayerStats' : IDL.Func([], [IDL.Vec(Player)], ['query']),
    'getAllTeams' : IDL.Func([], [IDL.Vec(Team)], ['query']),
    'getAllUserProfiles' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
    'getCallerAccountIds' : IDL.Func([], [IDL.Text, IDL.Text], ['query']),
    'getCallerAddresses' : IDL.Func([], [IDL.Text, IDL.Text], ['query']),
    'getCallerDerivedAccountId' : IDL.Func([], [IDL.Text], ['query']),
    'getCallerIcpBalance' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Nat, 'err' : IDL.Text })],
        [],
      ),
    'getCallerIcpTransactions' : IDL.Func(
        [],
        [IDL.Vec(TokenTransaction)],
        ['query'],
      ),
    'getCallerPrincipalId' : IDL.Func([], [IDL.Text], ['query']),
    'getCallerStkBalance' : IDL.Func([], [IDL.Nat], ['query']),
    'getCallerStkTransactions' : IDL.Func(
        [],
        [IDL.Vec(TokenTransaction)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCallerWallet' : IDL.Func([], [IDL.Opt(Wallet)], ['query']),
    'getCallerWalletSummary' : IDL.Func(
        [],
        [
          IDL.Nat,
          IDL.Vec(TokenTransaction),
          IDL.Vec(TokenTransaction),
          IDL.Text,
          IDL.Text,
        ],
        ['query'],
      ),
    'getFileReference' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(FileReference)],
        ['query'],
      ),
    'getGame' : IDL.Func([IDL.Nat], [IDL.Opt(Game)], ['query']),
    'getInvitations' : IDL.Func([], [IDL.Vec(Invitation)], ['query']),
    'getJoinRequests' : IDL.Func([], [IDL.Vec(JoinRequest)], ['query']),
    'getLeaderboard' : IDL.Func([], [IDL.Vec(Player)], ['query']),
    'getLedgerPrincipal' : IDL.Func(
        [],
        [IDL.Variant({ 'ok' : IDL.Principal, 'err' : IDL.Text })],
        ['query'],
      ),
    'getMessages' : IDL.Func([IDL.Nat], [IDL.Vec(ChatMessage)], ['query']),
    'getPaymentTransaction' : IDL.Func(
        [IDL.Nat],
        [IDL.Opt(PaymentTransaction)],
        [],
      ),
    'getPaymentTransactions' : IDL.Func([], [IDL.Vec(PaymentTransaction)], []),
    'getPlayerStats' : IDL.Func([IDL.Text], [IDL.Opt(Player)], ['query']),
    'getPoolManagementHistory' : IDL.Func(
        [],
        [IDL.Variant({ 'ok' : IDL.Vec(TokenTransaction), 'err' : IDL.Text })],
        ['query'],
      ),
    'getPriceFeed' : IDL.Func([IDL.Text], [IDL.Opt(PriceFeed)], []),
    'getPriceFeeds' : IDL.Func([], [IDL.Vec(PriceFeed)], []),
    'getRealTimePoolBalances' : IDL.Func(
        [],
        [IDL.Variant({ 'ok' : IDL.Vec(TokenPool), 'err' : IDL.Text })],
        ['query'],
      ),
    'getTeam' : IDL.Func([IDL.Nat], [IDL.Opt(Team)], ['query']),
    'getTokenPool' : IDL.Func([IDL.Text], [IDL.Opt(TokenPool)], []),
    'getTokenPools' : IDL.Func([], [IDL.Vec(TokenPool)], []),
    'getTokenTransaction' : IDL.Func(
        [IDL.Nat],
        [IDL.Opt(TokenTransaction)],
        [],
      ),
    'getTokenTransactions' : IDL.Func([], [IDL.Vec(TokenTransaction)], []),
    'getTotalSupply' : IDL.Func([], [IDL.Nat], []),
    'getTotalSupplyStatus' : IDL.Func(
        [],
        [IDL.Variant({ 'ok' : IDL.Nat, 'err' : IDL.Text })],
        ['query'],
      ),
    'getUserBalance' : IDL.Func([IDL.Principal], [IDL.Nat], []),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getWallet' : IDL.Func([IDL.Principal], [IDL.Opt(Wallet)], ['query']),
    'initializeAccessControl' : IDL.Func([], [], []),
    'initializeWallet' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'inviteToTeam' : IDL.Func([IDL.Nat, IDL.Principal], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'leaveTeam' : IDL.Func([IDL.Nat], [], []),
    'listFileReferences' : IDL.Func([], [IDL.Vec(FileReference)], ['query']),
    'loginUser' : IDL.Func(
        [],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'mintStkTokens' : IDL.Func(
        [IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'receiveStkTokens' : IDL.Func(
        [IDL.Nat],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'recomputeMyAccountId' : IDL.Func(
        [],
        [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
        [],
      ),
    'recordIcpSend' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Nat],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'recordPaymentTransaction' : IDL.Func(
        [IDL.Principal, IDL.Nat, IDL.Nat, IDL.Text, IDL.Opt(IDL.Text)],
        [IDL.Nat],
        [],
      ),
    'recordTokenTransaction' : IDL.Func(
        [
          IDL.Opt(IDL.Principal),
          IDL.Opt(IDL.Principal),
          IDL.Nat,
          IDL.Text,
          IDL.Opt(IDL.Text),
          IDL.Text,
          IDL.Opt(IDL.Text),
        ],
        [IDL.Nat],
        [],
      ),
    'registerFileReference' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'requestToJoinTeam' : IDL.Func([IDL.Nat], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'saveGame' : IDL.Func(
        [
          IDL.Vec(Player),
          IDL.Vec(IDL.Vec(Frame)),
          IDL.Vec(IDL.Nat),
          IDL.Opt(IDL.Principal),
        ],
        [IDL.Nat],
        [],
      ),
    'sendMessage' : IDL.Func([IDL.Text, IDL.Text, IDL.Nat], [], []),
    'sendStkTokens' : IDL.Func(
        [IDL.Text, IDL.Nat],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'setAdminIcpWallet' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'setAdminTreasuryAccount' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'setLedgerPrincipal' : IDL.Func(
        [IDL.Principal],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'transferTokensBetweenPools' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Nat],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'updateCallerAchievements' : IDL.Func([IDL.Vec(IDL.Text)], [], []),
    'updateCallerProfilePicture' : IDL.Func([IDL.Text], [], []),
    'updateCallerUserProfileStats' : IDL.Func(
        [IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat],
        [],
        [],
      ),
    'updateCallerWallet' : IDL.Func(
        [IDL.Nat],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'updatePlayerStats' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat],
        [],
        [],
      ),
    'updatePriceFeed' : IDL.Func([IDL.Text, IDL.Nat, IDL.Text], [], []),
    'updateTeamStats' : IDL.Func([IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat], [], []),
    'updateTokenPool' : IDL.Func([IDL.Text, IDL.Nat], [], []),
    'updateTotalSupply' : IDL.Func([IDL.Nat], [], []),
    'updateUserBalance' : IDL.Func([IDL.Principal, IDL.Nat], [], []),
    'verifyIcpPayment' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Nat, 'err' : IDL.Text })],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };