/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ChatMessage {
  'gameId' : bigint,
  'sender' : string,
  'message' : string,
  'timestamp' : bigint,
}
export interface FileReference { 'hash' : string, 'path' : string }
export interface Frame {
  'score' : bigint,
  'roll1' : bigint,
  'roll2' : bigint,
  'roll3' : [] | [bigint],
}
export interface Game {
  'id' : bigint,
  'totalScores' : Array<bigint>,
  'owner' : [] | [Principal],
  'players' : Array<Player>,
  'timestamp' : bigint,
  'frames' : Array<Array<Frame>>,
}
export interface Invitation {
  'invitee' : Principal,
  'inviter' : Principal,
  'timestamp' : bigint,
  'teamId' : bigint,
}
export interface JoinRequest {
  'requester' : Principal,
  'timestamp' : bigint,
  'teamId' : bigint,
}
export interface PaymentTransaction {
  'id' : bigint,
  'status' : string,
  'stkAmount' : bigint,
  'user' : Principal,
  'reference' : [] | [string],
  'exchangeRate' : bigint,
  'timestamp' : bigint,
  'icpAmount' : bigint,
}
export interface Player {
  'gamesPlayed' : bigint,
  'scores' : Array<bigint>,
  'name' : string,
  'highestScore' : bigint,
  'totalSpares' : bigint,
  'totalStrikes' : bigint,
  'totalPoints' : bigint,
  'averageScore' : bigint,
}
export interface PriceFeed {
  'status' : string,
  'source' : string,
  'icpUsd' : bigint,
  'lastUpdated' : bigint,
}
export interface Team {
  'id' : bigint,
  'creator' : Principal,
  'members' : Array<Principal>,
  'name' : string,
  'createdAt' : bigint,
  'description' : string,
  'bestScore' : bigint,
  'totalGames' : bigint,
  'averageScore' : bigint,
}
export interface TokenPool {
  'total' : bigint,
  'name' : string,
  'remaining' : bigint,
}
export interface TokenTransaction {
  'id' : bigint,
  'to' : [] | [Principal],
  'status' : string,
  'transactionType' : string,
  'from' : [] | [Principal],
  'pool' : [] | [string],
  'reference' : [] | [string],
  'timestamp' : bigint,
  'amount' : bigint,
  'ledgerHeight' : [] | [bigint],
}
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface UserProfile {
  'principal' : Principal,
  'displayName' : string,
  'gamesPlayed' : bigint,
  'highestScore' : bigint,
  'totalSpares' : bigint,
  'achievements' : Array<string>,
  'games' : Array<bigint>,
  'totalStrikes' : bigint,
  'totalPoints' : bigint,
  'profilePicture' : [] | [string],
  'averageScore' : bigint,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface Wallet {
  'stkPrincipalId' : string,
  'icpTransactions' : Array<TokenTransaction>,
  'icpAccountId' : string,
  'stkBalance' : bigint,
  'stkTransactions' : Array<TokenTransaction>,
}
export interface _ImmutableObjectStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _ImmutableObjectStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _ImmutableObjectStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_immutableObjectStorageBlobsAreLive' : ActorMethod<
    [Array<Uint8Array>],
    Array<boolean>
  >,
  '_immutableObjectStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_immutableObjectStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_immutableObjectStorageCreateCertificate' : ActorMethod<
    [string],
    _ImmutableObjectStorageCreateCertificateResult
  >,
  '_immutableObjectStorageRefillCashier' : ActorMethod<
    [[] | [_ImmutableObjectStorageRefillInformation]],
    _ImmutableObjectStorageRefillResult
  >,
  '_immutableObjectStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControl' : ActorMethod<[], undefined>,
  'acceptInvitation' : ActorMethod<[bigint], undefined>,
  'addIcpTransaction' : ActorMethod<
    [TokenTransaction],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'addStkTransaction' : ActorMethod<
    [TokenTransaction],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'adjustPoolAllocation' : ActorMethod<
    [string, bigint],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'approveJoinRequest' : ActorMethod<[bigint, Principal], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createTeam' : ActorMethod<[string, string], bigint>,
  'creditUserWallet' : ActorMethod<[Principal, bigint], undefined>,
  'declineInvitation' : ActorMethod<[bigint], undefined>,
  'denyJoinRequest' : ActorMethod<[bigint, Principal], undefined>,
  'dropFileReference' : ActorMethod<[string], undefined>,
  'fetchIcpPrice' : ActorMethod<[string], string>,
  'getAdminAuditTrail' : ActorMethod<
    [],
    { 'ok' : Array<TokenTransaction> } |
      { 'err' : string }
  >,
  'getAdminIcpWallet' : ActorMethod<[], [] | [string]>,
  'getAdminTreasuryAddress' : ActorMethod<[], [] | [string]>,
  'getAllGames' : ActorMethod<[bigint, bigint], Array<Game>>,
  'getAllMessages' : ActorMethod<[bigint, bigint], Array<ChatMessage>>,
  'getAllPlayerStats' : ActorMethod<[bigint, bigint], Array<Player>>,
  'getAllTeams' : ActorMethod<[bigint, bigint], Array<Team>>,
  'getAllUserProfiles' : ActorMethod<[bigint, bigint], Array<UserProfile>>,
  'getCallerAccountIds' : ActorMethod<[], [string, string]>,
  'getCallerAddresses' : ActorMethod<[], [string, string]>,
  'getCallerDerivedAccountId' : ActorMethod<[], string>,
  'getCallerIcpBalance' : ActorMethod<
    [string],
    { 'ok' : bigint } |
      { 'err' : string }
  >,
  'getCallerIcpTransactions' : ActorMethod<[], Array<TokenTransaction>>,
  'getCallerPrincipalId' : ActorMethod<[], string>,
  'getCallerStkBalance' : ActorMethod<[], bigint>,
  'getCallerStkTransactions' : ActorMethod<[], Array<TokenTransaction>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCallerWallet' : ActorMethod<[], [] | [Wallet]>,
  'getCallerWalletSummary' : ActorMethod<
    [],
    [bigint, Array<TokenTransaction>, Array<TokenTransaction>, string, string]
  >,
  'getFileReference' : ActorMethod<[string], [] | [FileReference]>,
  'getGame' : ActorMethod<[bigint], [] | [Game]>,
  'getInvitations' : ActorMethod<[bigint, bigint], Array<Invitation>>,
  'getJoinRequests' : ActorMethod<[bigint, bigint], Array<JoinRequest>>,
  'getLeaderboard' : ActorMethod<[bigint, bigint], Array<Player>>,
  'getLedgerPrincipal' : ActorMethod<
    [],
    { 'ok' : Principal } |
      { 'err' : string }
  >,
  'getMessages' : ActorMethod<[bigint, bigint, bigint], Array<ChatMessage>>,
  'getPaymentTransaction' : ActorMethod<[bigint], [] | [PaymentTransaction]>,
  'getPaymentTransactions' : ActorMethod<[], Array<PaymentTransaction>>,
  'getPlayerStats' : ActorMethod<[string], [] | [Player]>,
  'getPoolManagementHistory' : ActorMethod<
    [],
    { 'ok' : Array<TokenTransaction> } |
      { 'err' : string }
  >,
  'getPriceFeed' : ActorMethod<[string], [] | [PriceFeed]>,
  'getPriceFeeds' : ActorMethod<[], Array<PriceFeed>>,
  'getRealTimePoolBalances' : ActorMethod<
    [],
    { 'ok' : Array<TokenPool> } |
      { 'err' : string }
  >,
  'getTeam' : ActorMethod<[bigint], [] | [Team]>,
  'getTokenPool' : ActorMethod<[string], [] | [TokenPool]>,
  'getTokenPools' : ActorMethod<[], Array<TokenPool>>,
  'getTokenTransaction' : ActorMethod<[bigint], [] | [TokenTransaction]>,
  'getTokenTransactions' : ActorMethod<[], Array<TokenTransaction>>,
  'getCirculatingSupply' : ActorMethod<[], bigint>,
  'getTotalSupply' : ActorMethod<[], bigint>,
  'getTotalSupplyStatus' : ActorMethod<
    [],
    { 'ok' : bigint } |
      { 'err' : string }
  >,
  'getUserBalance' : ActorMethod<[Principal], bigint>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getWallet' : ActorMethod<[Principal], [] | [Wallet]>,
  'initializeAccessControl' : ActorMethod<[], undefined>,
  'initializeWallet' : ActorMethod<
    [string, string],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'inviteToTeam' : ActorMethod<[bigint, Principal], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'leaveTeam' : ActorMethod<[bigint], undefined>,
  'listFileReferences' : ActorMethod<[], Array<FileReference>>,
  'loginUser' : ActorMethod<[], { 'ok' : null } | { 'err' : string }>,
  'mintStkTokens' : ActorMethod<
    [bigint, bigint, bigint, bigint],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'receiveStkTokens' : ActorMethod<
    [bigint],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'recomputeMyAccountId' : ActorMethod<
    [],
    { 'ok' : string } |
      { 'err' : string }
  >,
  'recordIcpSend' : ActorMethod<
    [string, bigint, bigint],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'recordPaymentTransaction' : ActorMethod<
    [Principal, bigint, bigint, string, [] | [string]],
    bigint
  >,
  'recordTokenTransaction' : ActorMethod<
    [
      [] | [Principal],
      [] | [Principal],
      bigint,
      string,
      [] | [string],
      string,
      [] | [string],
    ],
    bigint
  >,
  'registerFileReference' : ActorMethod<[string, string], undefined>,
  'requestToJoinTeam' : ActorMethod<[bigint], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'saveGame' : ActorMethod<
    [Array<Player>, Array<Array<Frame>>, Array<bigint>],
    bigint
  >,
  'sendMessage' : ActorMethod<[string, bigint], undefined>,
  'sendStkTokens' : ActorMethod<
    [string, bigint],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'setAdminIcpWallet' : ActorMethod<
    [string],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'setAdminTreasuryAccount' : ActorMethod<
    [string],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'setLedgerPrincipal' : ActorMethod<
    [Principal],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'transferFromPoolToUser' : ActorMethod<
    [string, string, bigint],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'transferTokensBetweenPools' : ActorMethod<
    [string, string, bigint],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'updateCallerAchievements' : ActorMethod<[Array<string>], undefined>,
  'updateCallerProfilePicture' : ActorMethod<[string], undefined>,
  'updateCallerUserProfileStats' : ActorMethod<
    [bigint, bigint, bigint, bigint, bigint],
    undefined
  >,
  'updatePlayerStats' : ActorMethod<
    [string, bigint, bigint, bigint, bigint, bigint],
    undefined
  >,
  'updatePriceFeed' : ActorMethod<[string, bigint, string], undefined>,
  'updateTeamStats' : ActorMethod<[bigint, bigint, bigint, bigint], undefined>,
  'updateTokenPool' : ActorMethod<[string, bigint], undefined>,
  'updateUserBalance' : ActorMethod<[Principal, bigint], undefined>,
  'verifyIcpPayment' : ActorMethod<
    [string],
    { 'ok' : bigint } |
      { 'err' : string }
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];