export const idlFactory = ({ IDL }) => {
  const TokenTransaction = IDL.Record({
    'id' : IDL.Nat,
    'to' : IDL.Opt(IDL.Principal),
    'status' : IDL.Text,
    'transactionType' : IDL.Text,
    'from' : IDL.Opt(IDL.Principal),
    'pool' : IDL.Opt(IDL.Text),
    'reference' : IDL.Opt(IDL.Text),
    'timestamp' : IDL.Int,
    'amount' : IDL.Nat,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Player = IDL.Record({
    'gamesPlayed' : IDL.Nat,
    'scores' : IDL.Vec(IDL.Nat),
    'name' : IDL.Text,
    'highestScore' : IDL.Nat,
    'totalSpares' : IDL.Nat,
    'totalStrikes' : IDL.Nat,
    'totalPoints' : IDL.Nat,
    'averageScore' : IDL.Nat,
  });
  const Frame = IDL.Record({
    'score' : IDL.Nat,
    'roll1' : IDL.Nat,
    'roll2' : IDL.Nat,
    'roll3' : IDL.Opt(IDL.Nat),
  });
  const Game = IDL.Record({
    'id' : IDL.Nat,
    'totalScores' : IDL.Vec(IDL.Nat),
    'owner' : IDL.Opt(IDL.Principal),
    'players' : IDL.Vec(Player),
    'timestamp' : IDL.Int,
    'frames' : IDL.Vec(IDL.Vec(Frame)),
  });
  const ChatMessage = IDL.Record({
    'gameId' : IDL.Nat,
    'sender' : IDL.Text,
    'message' : IDL.Text,
    'timestamp' : IDL.Int,
  });
  const Team = IDL.Record({
    'id' : IDL.Nat,
    'creator' : IDL.Principal,
    'members' : IDL.Vec(IDL.Principal),
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'description' : IDL.Text,
    'bestScore' : IDL.Nat,
    'totalGames' : IDL.Nat,
    'averageScore' : IDL.Nat,
  });
  const UserProfile = IDL.Record({
    'principal' : IDL.Principal,
    'displayName' : IDL.Text,
    'gamesPlayed' : IDL.Nat,
    'highestScore' : IDL.Nat,
    'totalSpares' : IDL.Nat,
    'achievements' : IDL.Vec(IDL.Text),
    'games' : IDL.Vec(IDL.Nat),
    'totalStrikes' : IDL.Nat,
    'totalPoints' : IDL.Nat,
    'profilePicture' : IDL.Opt(IDL.Text),
    'averageScore' : IDL.Nat,
  });
  const Wallet = IDL.Record({
    'stkAccountId' : IDL.Text,
    'stkAddress' : IDL.Text,
    'icpBalance' : IDL.Nat,
    'icpTransactions' : IDL.Vec(TokenTransaction),
    'icpAccountId' : IDL.Text,
    'stkBalance' : IDL.Nat,
    'stkTransactions' : IDL.Vec(TokenTransaction),
    'icpAddress' : IDL.Text,
    'principalId' : IDL.Text,
  });
  const FileReference = IDL.Record({ 'hash' : IDL.Text, 'path' : IDL.Text });
  const Invitation = IDL.Record({
    'invitee' : IDL.Principal,
    'inviter' : IDL.Principal,
    'timestamp' : IDL.Int,
    'teamId' : IDL.Nat,
  });
  const JoinRequest = IDL.Record({
    'requester' : IDL.Principal,
    'timestamp' : IDL.Int,
    'teamId' : IDL.Nat,
  });
  const PaymentTransaction = IDL.Record({
    'id' : IDL.Nat,
    'status' : IDL.Text,
    'stkAmount' : IDL.Nat,
    'user' : IDL.Principal,
    'reference' : IDL.Opt(IDL.Text),
    'exchangeRate' : IDL.Nat,
    'timestamp' : IDL.Int,
    'icpAmount' : IDL.Nat,
  });
  const PriceFeed = IDL.Record({
    'status' : IDL.Text,
    'source' : IDL.Text,
    'icpUsd' : IDL.Nat,
    'lastUpdated' : IDL.Int,
  });
  const TokenPool = IDL.Record({
    'total' : IDL.Nat,
    'name' : IDL.Text,
    'remaining' : IDL.Nat,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  return IDL.Service({
    'acceptInvitation' : IDL.Func([IDL.Nat, IDL.Principal], [], []),
    'addIcpTransaction' : IDL.Func([TokenTransaction], [], []),
    'addStkTransaction' : IDL.Func([TokenTransaction], [], []),
    'adjustPoolAllocation' : IDL.Func([IDL.Text, IDL.Nat], [], []),
    'approveJoinRequest' : IDL.Func(
        [IDL.Nat, IDL.Principal, IDL.Principal],
        [],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createTeam' : IDL.Func([IDL.Text, IDL.Text, IDL.Principal], [IDL.Nat], []),
    'declineInvitation' : IDL.Func([IDL.Nat, IDL.Principal], [], []),
    'denyJoinRequest' : IDL.Func(
        [IDL.Nat, IDL.Principal, IDL.Principal],
        [],
        [],
      ),
    'dropFileReference' : IDL.Func([IDL.Text], [], []),
    'fetchIcpPrice' : IDL.Func([], [IDL.Text], []),
    'fetchIcpPriceFromBinance' : IDL.Func([], [IDL.Text], []),
    'fetchIcpPriceFromBitfinex' : IDL.Func([], [IDL.Text], []),
    'fetchIcpPriceFromBitflyer' : IDL.Func([], [IDL.Text], []),
    'fetchIcpPriceFromBitget' : IDL.Func([], [IDL.Text], []),
    'fetchIcpPriceFromBithumb' : IDL.Func([], [IDL.Text], []),
    'fetchIcpPriceFromBitmart' : IDL.Func([], [IDL.Text], []),
    'fetchIcpPriceFromBitstamp' : IDL.Func([], [IDL.Text], []),
    'fetchIcpPriceFromBittrex' : IDL.Func([], [IDL.Text], []),
    'fetchIcpPriceFromBybit' : IDL.Func([], [IDL.Text], []),
    'fetchIcpPriceFromCoinMarketCap' : IDL.Func([], [IDL.Text], []),
    'fetchIcpPriceFromCoinbase' : IDL.Func([], [IDL.Text], []),
    'fetchIcpPriceFromCoinbaseAdvanced' : IDL.Func([], [IDL.Text], []),
    'fetchIcpPriceFromCoinbaseCard' : IDL.Func([], [IDL.Text], []),
    'fetchIcpPriceFromCoinbaseCommerce' : IDL.Func([], [IDL.Text], []),
    'fetchIcpPriceFromCoinbaseCustody' : IDL.Func([], [IDL.Text], []),
    'fetchIcpPriceFromCoinbaseEarn' : IDL.Func([], [IDL.Text], []),
    'fetchIcpPriceFromCoinbaseInstitutional' : IDL.Func([], [IDL.Text], []),
    'fetchIcpPriceFromCoinbaseLearn' : IDL.Func([], [IDL.Text], []),
    'fetchIcpPriceFromCoinbasePrime' : IDL.Func([], [IDL.Text], []),
    'fetchIcpPriceFromCoinbasePrimeApi' : IDL.Func([], [IDL.Text], []),
    'fetchIcpPriceFromCoinbasePro' : IDL.Func([], [IDL.Text], []),
    'fetchIcpPriceFromCoinbaseProApi' : IDL.Func([], [IDL.Text], []),
    'fetchIcpPriceFromCoinbaseWallet' : IDL.Func([], [IDL.Text], []),
    'fetchIcpPriceFromCoincheck' : IDL.Func([], [IDL.Text], []),
    'fetchIcpPriceFromCoinlist' : IDL.Func([], [IDL.Text], []),
    'fetchIcpPriceFromCoinone' : IDL.Func([], [IDL.Text], []),
    'fetchIcpPriceFromCoinoneUsd' : IDL.Func([], [IDL.Text], []),
    'fetchIcpPriceFromGateIo' : IDL.Func([], [IDL.Text], []),
    'fetchIcpPriceFromGemini' : IDL.Func([], [IDL.Text], []),
    'fetchIcpPriceFromHuobi' : IDL.Func([], [IDL.Text], []),
    'fetchIcpPriceFromKraken' : IDL.Func([], [IDL.Text], []),
    'fetchIcpPriceFromKuCoin' : IDL.Func([], [IDL.Text], []),
    'fetchIcpPriceFromLiquid' : IDL.Func([], [IDL.Text], []),
    'fetchIcpPriceFromMexc' : IDL.Func([], [IDL.Text], []),
    'fetchIcpPriceFromOkx' : IDL.Func([], [IDL.Text], []),
    'fetchIcpPriceFromPhemex' : IDL.Func([], [IDL.Text], []),
    'fetchIcpPriceFromPoloniex' : IDL.Func([], [IDL.Text], []),
    'fetchIcpPriceFromProbit' : IDL.Func([], [IDL.Text], []),
    'fetchIcpPriceFromUpbit' : IDL.Func([], [IDL.Text], []),
    'getAdminAuditTrail' : IDL.Func([], [IDL.Vec(TokenTransaction)], ['query']),
    'getAllGames' : IDL.Func([], [IDL.Vec(Game)], ['query']),
    'getAllMessages' : IDL.Func([], [IDL.Vec(ChatMessage)], ['query']),
    'getAllPlayerStats' : IDL.Func([], [IDL.Vec(Player)], ['query']),
    'getAllTeams' : IDL.Func([], [IDL.Vec(Team)], ['query']),
    'getAllUserProfiles' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
    'getCallerAccountIds' : IDL.Func([], [IDL.Text, IDL.Text], ['query']),
    'getCallerAddresses' : IDL.Func([], [IDL.Text, IDL.Text], ['query']),
    'getCallerIcpBalance' : IDL.Func([], [IDL.Nat], ['query']),
    'getCallerIcpTransactions' : IDL.Func(
        [],
        [IDL.Vec(TokenTransaction)],
        ['query'],
      ),
    'getCallerPrincipalId' : IDL.Func([], [IDL.Text], ['query']),
    'getCallerStkBalance' : IDL.Func([], [IDL.Nat], ['query']),
    'getCallerStkTransactions' : IDL.Func(
        [],
        [IDL.Vec(TokenTransaction)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCallerWallet' : IDL.Func([], [IDL.Opt(Wallet)], ['query']),
    'getCallerWalletSummary' : IDL.Func(
        [],
        [
          IDL.Nat,
          IDL.Nat,
          IDL.Vec(TokenTransaction),
          IDL.Vec(TokenTransaction),
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
        ],
        ['query'],
      ),
    'getFileReference' : IDL.Func([IDL.Text], [FileReference], ['query']),
    'getGame' : IDL.Func([IDL.Nat], [IDL.Opt(Game)], ['query']),
    'getInvitations' : IDL.Func([], [IDL.Vec(Invitation)], ['query']),
    'getJoinRequests' : IDL.Func([], [IDL.Vec(JoinRequest)], ['query']),
    'getLeaderboard' : IDL.Func([], [IDL.Vec(Player)], ['query']),
    'getMessages' : IDL.Func([IDL.Nat], [IDL.Vec(ChatMessage)], ['query']),
    'getPaymentTransaction' : IDL.Func(
        [IDL.Nat],
        [IDL.Opt(PaymentTransaction)],
        [],
      ),
    'getPaymentTransactions' : IDL.Func([], [IDL.Vec(PaymentTransaction)], []),
    'getPlayerStats' : IDL.Func([IDL.Text], [IDL.Opt(Player)], ['query']),
    'getPoolManagementHistory' : IDL.Func(
        [],
        [IDL.Vec(TokenTransaction)],
        ['query'],
      ),
    'getPriceFeed' : IDL.Func([IDL.Text], [IDL.Opt(PriceFeed)], []),
    'getPriceFeeds' : IDL.Func([], [IDL.Vec(PriceFeed)], []),
    'getRealTimePoolBalances' : IDL.Func([], [IDL.Vec(TokenPool)], ['query']),
    'getTeam' : IDL.Func([IDL.Nat], [IDL.Opt(Team)], ['query']),
    'getTokenPool' : IDL.Func([IDL.Text], [IDL.Opt(TokenPool)], []),
    'getTokenPools' : IDL.Func([], [IDL.Vec(TokenPool)], []),
    'getTokenTransaction' : IDL.Func(
        [IDL.Nat],
        [IDL.Opt(TokenTransaction)],
        [],
      ),
    'getTokenTransactions' : IDL.Func([], [IDL.Vec(TokenTransaction)], []),
    'getTotalSupply' : IDL.Func([], [IDL.Nat], []),
    'getTotalSupplyStatus' : IDL.Func([], [IDL.Nat], ['query']),
    'getUserBalance' : IDL.Func([IDL.Principal], [IDL.Nat], []),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getWallet' : IDL.Func([IDL.Principal], [IDL.Opt(Wallet)], ['query']),
    'initializeAccessControl' : IDL.Func([], [], []),
    'initializeWallet' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'inviteToTeam' : IDL.Func([IDL.Nat, IDL.Principal, IDL.Principal], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'leaveTeam' : IDL.Func([IDL.Nat, IDL.Principal], [], []),
    'listFileReferences' : IDL.Func([], [IDL.Vec(FileReference)], ['query']),
    'receiveIcpTokens' : IDL.Func([IDL.Nat], [], []),
    'receiveStkTokens' : IDL.Func([IDL.Nat], [], []),
    'recordPaymentTransaction' : IDL.Func(
        [IDL.Principal, IDL.Nat, IDL.Nat, IDL.Nat, IDL.Text, IDL.Opt(IDL.Text)],
        [IDL.Nat],
        [],
      ),
    'recordTokenTransaction' : IDL.Func(
        [
          IDL.Opt(IDL.Principal),
          IDL.Opt(IDL.Principal),
          IDL.Nat,
          IDL.Text,
          IDL.Opt(IDL.Text),
          IDL.Text,
          IDL.Opt(IDL.Text),
        ],
        [IDL.Nat],
        [],
      ),
    'registerFileReference' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'requestToJoinTeam' : IDL.Func([IDL.Nat, IDL.Principal], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'saveGame' : IDL.Func(
        [
          IDL.Vec(Player),
          IDL.Vec(IDL.Vec(Frame)),
          IDL.Vec(IDL.Nat),
          IDL.Opt(IDL.Principal),
        ],
        [IDL.Nat],
        [],
      ),
    'sendIcpTokens' : IDL.Func([IDL.Text, IDL.Nat], [], []),
    'sendMessage' : IDL.Func([IDL.Text, IDL.Text, IDL.Nat], [], []),
    'sendStkTokens' : IDL.Func([IDL.Text, IDL.Nat], [], []),
    'transferTokensBetweenPools' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Nat],
        [],
        [],
      ),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'updateAchievements' : IDL.Func([IDL.Principal, IDL.Vec(IDL.Text)], [], []),
    'updateCallerWallet' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
    'updatePlayerStats' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat],
        [],
        [],
      ),
    'updatePriceFeed' : IDL.Func([IDL.Text, IDL.Nat, IDL.Text], [], []),
    'updateProfilePicture' : IDL.Func([IDL.Principal, IDL.Text], [], []),
    'updateTeamStats' : IDL.Func([IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat], [], []),
    'updateTokenPool' : IDL.Func([IDL.Text, IDL.Nat], [], []),
    'updateTotalSupply' : IDL.Func([IDL.Nat], [], []),
    'updateUserBalance' : IDL.Func([IDL.Principal, IDL.Nat], [], []),
    'updateUserProfileStats' : IDL.Func(
        [IDL.Principal, IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat],
        [],
        [],
      ),
  });
};
export const init = ({ IDL }) => { return []; };
