/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Player {
    gamesPlayed: bigint;
    scores: Array<bigint>;
    name: string;
    highestScore: bigint;
    totalSpares: bigint;
    totalStrikes: bigint;
    totalPoints: bigint;
    averageScore: bigint;
}
export interface JoinRequest {
    requester: Principal;
    timestamp: bigint;
    teamId: bigint;
}
export interface Game {
    id: bigint;
    totalScores: Array<bigint>;
    owner?: Principal;
    players: Array<Player>;
    timestamp: bigint;
    frames: Array<Array<Frame>>;
}
export interface TransformationOutput {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export interface TokenTransaction {
    id: bigint;
    to?: Principal;
    status: string;
    transactionType: string;
    from?: Principal;
    pool?: string;
    reference?: string;
    timestamp: bigint;
    amount: bigint;
    ledgerHeight?: bigint;
}
export interface _ImmutableObjectStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface _ImmutableObjectStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface Invitation {
    invitee: Principal;
    inviter: Principal;
    timestamp: bigint;
    teamId: bigint;
}
export interface TokenPool {
    total: bigint;
    name: string;
    remaining: bigint;
}
export interface PaymentTransaction {
    id: bigint;
    status: string;
    stkAmount: bigint;
    user: Principal;
    reference?: string;
    exchangeRate: bigint;
    timestamp: bigint;
    icpAmount: bigint;
}
export interface http_header {
    value: string;
    name: string;
}
export interface _ImmutableObjectStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export interface http_request_result {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export interface Frame {
    score: bigint;
    roll1: bigint;
    roll2: bigint;
    roll3?: bigint;
}
export interface Wallet {
    stkPrincipalId: string;
    icpTransactions: Array<TokenTransaction>;
    icpAccountId: string;
    stkBalance: bigint;
    stkTransactions: Array<TokenTransaction>;
}
export interface PriceFeed {
    status: string;
    source: string;
    icpUsd: bigint;
    lastUpdated: bigint;
}
export interface TransformationInput {
    context: Uint8Array;
    response: http_request_result;
}
export interface ChatMessage {
    gameId: bigint;
    sender: string;
    message: string;
    timestamp: bigint;
}
export interface FileReference {
    hash: string;
    path: string;
}
export interface UserProfile {
    principal: Principal;
    displayName: string;
    gamesPlayed: bigint;
    highestScore: bigint;
    totalSpares: bigint;
    achievements: Array<string>;
    games: Array<bigint>;
    totalStrikes: bigint;
    totalPoints: bigint;
    profilePicture?: string;
    averageScore: bigint;
}
export interface Team {
    id: bigint;
    creator: Principal;
    members: Array<Principal>;
    name: string;
    createdAt: bigint;
    description: string;
    bestScore: bigint;
    totalGames: bigint;
    averageScore: bigint;
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _immutableObjectStorageBlobsAreLive(hashes: Array<Uint8Array>): Promise<Array<boolean>>;
    _immutableObjectStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _immutableObjectStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _immutableObjectStorageCreateCertificate(blobHash: string): Promise<_ImmutableObjectStorageCreateCertificateResult>;
    _immutableObjectStorageRefillCashier(refillInformation: _ImmutableObjectStorageRefillInformation | null): Promise<_ImmutableObjectStorageRefillResult>;
    _immutableObjectStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControl(): Promise<void>;
    acceptInvitation(teamId: bigint): Promise<void>;
    addIcpTransaction(transaction: TokenTransaction): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }>;
    addStkTransaction(transaction: TokenTransaction): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }>;
    adjustPoolAllocation(poolName: string, newTotal: bigint): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }>;
    approveJoinRequest(teamId: bigint, requester: Principal): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createTeam(name: string, description: string): Promise<bigint>;
    creditUserWallet(user: Principal, stkAmount: bigint): Promise<void>;
    declineInvitation(teamId: bigint): Promise<void>;
    denyJoinRequest(teamId: bigint, requester: Principal): Promise<void>;
    dropFileReference(path: string): Promise<void>;
    fetchIcpPrice(source: string): Promise<string>;
    getAdminAuditTrail(): Promise<{
        __kind__: "ok";
        ok: Array<TokenTransaction>;
    } | {
        __kind__: "err";
        err: string;
    }>;
    getAdminIcpWallet(): Promise<string | null>;
    getAdminTreasuryAddress(): Promise<string | null>;
    getAllGames(offset: bigint, limit: bigint): Promise<Array<Game>>;
    getAllMessages(offset: bigint, limit: bigint): Promise<Array<ChatMessage>>;
    getAllPlayerStats(offset: bigint, limit: bigint): Promise<Array<Player>>;
    getAllTeams(offset: bigint, limit: bigint): Promise<Array<Team>>;
    getAllUserProfiles(offset: bigint, limit: bigint): Promise<Array<UserProfile>>;
    getCallerAccountIds(): Promise<[string, string]>;
    getCallerAddresses(): Promise<[string, string]>;
    getCallerDerivedAccountId(): Promise<string>;
    getCallerIcpBalance(accountIdText: string): Promise<{
        __kind__: "ok";
        ok: bigint;
    } | {
        __kind__: "err";
        err: string;
    }>;
    getCallerIcpTransactions(): Promise<Array<TokenTransaction>>;
    getCallerPrincipalId(): Promise<string>;
    getCallerStkBalance(): Promise<bigint>;
    getCallerStkTransactions(): Promise<Array<TokenTransaction>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getCallerWallet(): Promise<Wallet | null>;
    getCallerWalletSummary(): Promise<[bigint, Array<TokenTransaction>, Array<TokenTransaction>, string, string]>;
    getFileReference(path: string): Promise<FileReference | null>;
    getGame(gameId: bigint): Promise<Game | null>;
    getInvitations(offset: bigint, limit: bigint): Promise<Array<Invitation>>;
    getJoinRequests(offset: bigint, limit: bigint): Promise<Array<JoinRequest>>;
    getLeaderboard(offset: bigint, limit: bigint): Promise<Array<Player>>;
    getLedgerPrincipal(): Promise<{
        __kind__: "ok";
        ok: Principal;
    } | {
        __kind__: "err";
        err: string;
    }>;
    getMessages(gameId: bigint, offset: bigint, limit: bigint): Promise<Array<ChatMessage>>;
    getPaymentTransaction(id: bigint): Promise<PaymentTransaction | null>;
    getPaymentTransactions(): Promise<Array<PaymentTransaction>>;
    getPlayerStats(playerName: string): Promise<Player | null>;
    getPoolManagementHistory(): Promise<{
        __kind__: "ok";
        ok: Array<TokenTransaction>;
    } | {
        __kind__: "err";
        err: string;
    }>;
    getPriceFeed(source: string): Promise<PriceFeed | null>;
    getPriceFeeds(): Promise<Array<PriceFeed>>;
    getRealTimePoolBalances(): Promise<{
        __kind__: "ok";
        ok: Array<TokenPool>;
    } | {
        __kind__: "err";
        err: string;
    }>;
    getTeam(teamId: bigint): Promise<Team | null>;
    getTokenPool(name: string): Promise<TokenPool | null>;
    getTokenPools(): Promise<Array<TokenPool>>;
    getTokenTransaction(id: bigint): Promise<TokenTransaction | null>;
    getTokenTransactions(): Promise<Array<TokenTransaction>>;
    getTotalSupply(): Promise<bigint>;
    getTotalSupplyStatus(): Promise<{
        __kind__: "ok";
        ok: bigint;
    } | {
        __kind__: "err";
        err: string;
    }>;
    getUserBalance(user: Principal): Promise<bigint>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    getWallet(user: Principal): Promise<Wallet | null>;
    initializeAccessControl(): Promise<void>;
    initializeWallet(_icpAccountId: string, stkPrincipalId: string): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }>;
    inviteToTeam(teamId: bigint, invitee: Principal): Promise<void>;
    isCallerAdmin(): Promise<boolean>;
    leaveTeam(teamId: bigint): Promise<void>;
    listFileReferences(): Promise<Array<FileReference>>;
    loginUser(): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }>;
    mintStkTokens(icpAmount: bigint, stkAmount: bigint, exchangeRate: bigint, icpBlockHeight: bigint): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }>;
    receiveStkTokens(amount: bigint): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }>;
    recomputeMyAccountId(): Promise<{
        __kind__: "ok";
        ok: string;
    } | {
        __kind__: "err";
        err: string;
    }>;
    recordIcpSend(recipientAccountId: string, amount: bigint, blockHeight: bigint): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }>;
    recordPaymentTransaction(user: Principal, icpAmount: bigint, exchangeRate: bigint, status: string, reference: string | null): Promise<bigint>;
    recordTokenTransaction(from: Principal | null, to: Principal | null, amount: bigint, transactionType: string, pool: string | null, status: string, reference: string | null): Promise<bigint>;
    registerFileReference(path: string, hash: string): Promise<void>;
    requestToJoinTeam(teamId: bigint): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    saveGame(players: Array<Player>, frames: Array<Array<Frame>>, totalScores: Array<bigint>): Promise<bigint>;
    sendMessage(message: string, gameId: bigint): Promise<void>;
    sendStkTokens(recipient: string, amount: bigint): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }>;
    setAdminIcpWallet(address: string): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }>;
    setAdminTreasuryAccount(accountId: string): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }>;
    setLedgerPrincipal(p: Principal): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }>;
    transferFromPoolToUser(poolName: string, recipient: string, amount: bigint): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }>;
    transferTokensBetweenPools(sourcePool: string, destinationPool: string, amount: bigint): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }>;
    transform(input: TransformationInput): Promise<TransformationOutput>;
    updateCallerAchievements(achievements: Array<string>): Promise<void>;
    updateCallerProfilePicture(picturePath: string): Promise<void>;
    updateCallerUserProfileStats(totalSpares: bigint, totalStrikes: bigint, totalPoints: bigint, highestScore: bigint, gamesPlayed: bigint): Promise<void>;
    updatePlayerStats(name: string, totalSpares: bigint, totalStrikes: bigint, totalPoints: bigint, highestScore: bigint, gamesPlayed: bigint): Promise<void>;
    updatePriceFeed(source: string, icpUsd: bigint, status: string): Promise<void>;
    updateTeamStats(teamId: bigint, averageScore: bigint, totalGames: bigint, bestScore: bigint): Promise<void>;
    updateTokenPool(name: string, remaining: bigint): Promise<void>;
    updateTotalSupply(amount: bigint): Promise<void>;
    updateUserBalance(user: Principal, amount: bigint): Promise<void>;
    verifyIcpPayment(accountIdText: string): Promise<{
        __kind__: "ok";
        ok: bigint;
    } | {
        __kind__: "err";
        err: string;
    }>;
}
import type { FileReference as _FileReference, Frame as _Frame, Game as _Game, PaymentTransaction as _PaymentTransaction, Player as _Player, PriceFeed as _PriceFeed, Team as _Team, TokenPool as _TokenPool, TokenTransaction as _TokenTransaction, UserProfile as _UserProfile, UserRole as _UserRole, Wallet as _Wallet, _ImmutableObjectStorageRefillInformation as __ImmutableObjectStorageRefillInformation, _ImmutableObjectStorageRefillResult as __ImmutableObjectStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _immutableObjectStorageBlobsAreLive(arg0: Array<Uint8Array>): Promise<Array<boolean>> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageBlobsAreLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageBlobsAreLive(arg0);
            return result;
        }
    }
    async _immutableObjectStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageBlobsToDelete();
            return result;
        }
    }
    async _immutableObjectStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _immutableObjectStorageCreateCertificate(arg0: string): Promise<_ImmutableObjectStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _immutableObjectStorageRefillCashier(arg0: _ImmutableObjectStorageRefillInformation | null): Promise<_ImmutableObjectStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__ImmutableObjectStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__ImmutableObjectStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _immutableObjectStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControl(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControl();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControl();
            return result;
        }
    }
    async acceptInvitation(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.acceptInvitation(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.acceptInvitation(arg0);
            return result;
        }
    }
    async addIcpTransaction(arg0: TokenTransaction): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.addIcpTransaction(to_candid_TokenTransaction_n8(this._uploadFile, this._downloadFile, arg0));
                return from_candid_variant_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addIcpTransaction(to_candid_TokenTransaction_n8(this._uploadFile, this._downloadFile, arg0));
            return from_candid_variant_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async addStkTransaction(arg0: TokenTransaction): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.addStkTransaction(to_candid_TokenTransaction_n8(this._uploadFile, this._downloadFile, arg0));
                return from_candid_variant_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addStkTransaction(to_candid_TokenTransaction_n8(this._uploadFile, this._downloadFile, arg0));
            return from_candid_variant_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async adjustPoolAllocation(arg0: string, arg1: bigint): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.adjustPoolAllocation(arg0, arg1);
                return from_candid_variant_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adjustPoolAllocation(arg0, arg1);
            return from_candid_variant_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async approveJoinRequest(arg0: bigint, arg1: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.approveJoinRequest(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.approveJoinRequest(arg0, arg1);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n11(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n11(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createTeam(arg0: string, arg1: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createTeam(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createTeam(arg0, arg1);
            return result;
        }
    }
    async creditUserWallet(arg0: Principal, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.creditUserWallet(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.creditUserWallet(arg0, arg1);
            return result;
        }
    }
    async declineInvitation(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.declineInvitation(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.declineInvitation(arg0);
            return result;
        }
    }
    async denyJoinRequest(arg0: bigint, arg1: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.denyJoinRequest(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.denyJoinRequest(arg0, arg1);
            return result;
        }
    }
    async dropFileReference(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.dropFileReference(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.dropFileReference(arg0);
            return result;
        }
    }
    async fetchIcpPrice(arg0: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.fetchIcpPrice(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.fetchIcpPrice(arg0);
            return result;
        }
    }
    async getAdminAuditTrail(): Promise<{
        __kind__: "ok";
        ok: Array<TokenTransaction>;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getAdminAuditTrail();
                return from_candid_variant_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAdminAuditTrail();
            return from_candid_variant_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAdminIcpWallet(): Promise<string | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getAdminIcpWallet();
                return from_candid_opt_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAdminIcpWallet();
            return from_candid_opt_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAdminTreasuryAddress(): Promise<string | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getAdminTreasuryAddress();
                return from_candid_opt_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAdminTreasuryAddress();
            return from_candid_opt_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllGames(offset: bigint, limit: bigint): Promise<Array<Game>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllGames(offset, limit);
                return from_candid_vec_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllGames(offset, limit);
            return from_candid_vec_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllMessages(offset: bigint, limit: bigint): Promise<Array<ChatMessage>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllMessages(offset, limit);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllMessages(offset, limit);
            return result;
        }
    }
    async getAllPlayerStats(offset: bigint, limit: bigint): Promise<Array<Player>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllPlayerStats(offset, limit);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllPlayerStats(offset, limit);
            return result;
        }
    }
    async getAllTeams(offset: bigint, limit: bigint): Promise<Array<Team>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllTeams(offset, limit);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllTeams(offset, limit);
            return result;
        }
    }
    async getAllUserProfiles(offset: bigint, limit: bigint): Promise<Array<UserProfile>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllUserProfiles(offset, limit);
                return from_candid_vec_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllUserProfiles(offset, limit);
            return from_candid_vec_n26(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerAccountIds(): Promise<[string, string]> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerAccountIds();
                return [
                    result[0],
                    result[1]
                ];
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerAccountIds();
            return [
                result[0],
                result[1]
            ];
        }
    }
    async getCallerAddresses(): Promise<[string, string]> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerAddresses();
                return [
                    result[0],
                    result[1]
                ];
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerAddresses();
            return [
                result[0],
                result[1]
            ];
        }
    }
    async getCallerDerivedAccountId(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerDerivedAccountId();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerDerivedAccountId();
            return result;
        }
    }
    async getCallerIcpBalance(arg0: string): Promise<{
        __kind__: "ok";
        ok: bigint;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerIcpBalance(arg0);
                return from_candid_variant_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerIcpBalance(arg0);
            return from_candid_variant_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerIcpTransactions(): Promise<Array<TokenTransaction>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerIcpTransactions();
                return from_candid_vec_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerIcpTransactions();
            return from_candid_vec_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerPrincipalId(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerPrincipalId();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerPrincipalId();
            return result;
        }
    }
    async getCallerStkBalance(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerStkBalance();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerStkBalance();
            return result;
        }
    }
    async getCallerStkTransactions(): Promise<Array<TokenTransaction>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerStkTransactions();
                return from_candid_vec_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerStkTransactions();
            return from_candid_vec_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n30(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n30(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n31(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n31(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerWallet(): Promise<Wallet | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerWallet();
                return from_candid_opt_n33(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerWallet();
            return from_candid_opt_n33(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerWalletSummary(): Promise<[bigint, Array<TokenTransaction>, Array<TokenTransaction>, string, string]> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerWalletSummary();
                return [
                    result[0],
                    from_candid_vec_n14(this._uploadFile, this._downloadFile, result[1]),
                    from_candid_vec_n14(this._uploadFile, this._downloadFile, result[2]),
                    result[3],
                    result[4]
                ];
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerWalletSummary();
            return [
                result[0],
                from_candid_vec_n14(this._uploadFile, this._downloadFile, result[1]),
                from_candid_vec_n14(this._uploadFile, this._downloadFile, result[2]),
                result[3],
                result[4]
            ];
        }
    }
    async getFileReference(arg0: string): Promise<FileReference | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getFileReference(arg0);
                return from_candid_opt_n36(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFileReference(arg0);
            return from_candid_opt_n36(this._uploadFile, this._downloadFile, result);
        }
    }
    async getGame(arg0: bigint): Promise<Game | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getGame(arg0);
                return from_candid_opt_n37(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getGame(arg0);
            return from_candid_opt_n37(this._uploadFile, this._downloadFile, result);
        }
    }
    async getInvitations(offset: bigint, limit: bigint): Promise<Array<Invitation>> {
        if (this.processError) {
            try {
                const result = await this.actor.getInvitations(offset, limit);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getInvitations(offset, limit);
            return result;
        }
    }
    async getJoinRequests(offset: bigint, limit: bigint): Promise<Array<JoinRequest>> {
        if (this.processError) {
            try {
                const result = await this.actor.getJoinRequests(offset, limit);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getJoinRequests(offset, limit);
            return result;
        }
    }
    async getLeaderboard(offset: bigint, limit: bigint): Promise<Array<Player>> {
        if (this.processError) {
            try {
                const result = await this.actor.getLeaderboard(offset, limit);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLeaderboard(offset, limit);
            return result;
        }
    }
    async getLedgerPrincipal(): Promise<{
        __kind__: "ok";
        ok: Principal;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getLedgerPrincipal();
                return from_candid_variant_n38(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLedgerPrincipal();
            return from_candid_variant_n38(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMessages(arg0: bigint, offset: bigint, limit: bigint): Promise<Array<ChatMessage>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMessages(arg0, offset, limit);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMessages(arg0, offset, limit);
            return result;
        }
    }
    async getPaymentTransaction(arg0: bigint): Promise<PaymentTransaction | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getPaymentTransaction(arg0);
                return from_candid_opt_n39(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPaymentTransaction(arg0);
            return from_candid_opt_n39(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPaymentTransactions(): Promise<Array<PaymentTransaction>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPaymentTransactions();
                return from_candid_vec_n42(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPaymentTransactions();
            return from_candid_vec_n42(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPlayerStats(arg0: string): Promise<Player | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getPlayerStats(arg0);
                return from_candid_opt_n43(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPlayerStats(arg0);
            return from_candid_opt_n43(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPoolManagementHistory(): Promise<{
        __kind__: "ok";
        ok: Array<TokenTransaction>;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getPoolManagementHistory();
                return from_candid_variant_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPoolManagementHistory();
            return from_candid_variant_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPriceFeed(arg0: string): Promise<PriceFeed | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getPriceFeed(arg0);
                return from_candid_opt_n44(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPriceFeed(arg0);
            return from_candid_opt_n44(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPriceFeeds(): Promise<Array<PriceFeed>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPriceFeeds();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPriceFeeds();
            return result;
        }
    }
    async getRealTimePoolBalances(): Promise<{
        __kind__: "ok";
        ok: Array<TokenPool>;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getRealTimePoolBalances();
                return from_candid_variant_n45(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRealTimePoolBalances();
            return from_candid_variant_n45(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTeam(arg0: bigint): Promise<Team | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getTeam(arg0);
                return from_candid_opt_n46(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTeam(arg0);
            return from_candid_opt_n46(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTokenPool(arg0: string): Promise<TokenPool | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getTokenPool(arg0);
                return from_candid_opt_n47(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTokenPool(arg0);
            return from_candid_opt_n47(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTokenPools(): Promise<Array<TokenPool>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTokenPools();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTokenPools();
            return result;
        }
    }
    async getTokenTransaction(arg0: bigint): Promise<TokenTransaction | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getTokenTransaction(arg0);
                return from_candid_opt_n48(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTokenTransaction(arg0);
            return from_candid_opt_n48(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTokenTransactions(): Promise<Array<TokenTransaction>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTokenTransactions();
                return from_candid_vec_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTokenTransactions();
            return from_candid_vec_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTotalSupply(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getTotalSupply();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTotalSupply();
            return result;
        }
    }
    async getTotalSupplyStatus(): Promise<{
        __kind__: "ok";
        ok: bigint;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getTotalSupplyStatus();
                return from_candid_variant_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTotalSupplyStatus();
            return from_candid_variant_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserBalance(arg0: Principal): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserBalance(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserBalance(arg0);
            return result;
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n30(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n30(this._uploadFile, this._downloadFile, result);
        }
    }
    async getWallet(arg0: Principal): Promise<Wallet | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getWallet(arg0);
                return from_candid_opt_n33(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getWallet(arg0);
            return from_candid_opt_n33(this._uploadFile, this._downloadFile, result);
        }
    }
    async initializeAccessControl(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.initializeAccessControl();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.initializeAccessControl();
            return result;
        }
    }
    async initializeWallet(arg0: string, arg1: string): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.initializeWallet(arg0, arg1);
                return from_candid_variant_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.initializeWallet(arg0, arg1);
            return from_candid_variant_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async inviteToTeam(arg0: bigint, arg1: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.inviteToTeam(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.inviteToTeam(arg0, arg1);
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async leaveTeam(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.leaveTeam(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.leaveTeam(arg0);
            return result;
        }
    }
    async listFileReferences(): Promise<Array<FileReference>> {
        if (this.processError) {
            try {
                const result = await this.actor.listFileReferences();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listFileReferences();
            return result;
        }
    }
    async loginUser(): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.loginUser();
                return from_candid_variant_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.loginUser();
            return from_candid_variant_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async mintStkTokens(arg0: bigint, arg1: bigint, arg2: bigint, arg3: bigint): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.mintStkTokens(arg0, arg1, arg2, arg3);
                return from_candid_variant_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.mintStkTokens(arg0, arg1, arg2, arg3);
            return from_candid_variant_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async receiveStkTokens(arg0: bigint): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.receiveStkTokens(arg0);
                return from_candid_variant_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.receiveStkTokens(arg0);
            return from_candid_variant_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async recomputeMyAccountId(): Promise<{
        __kind__: "ok";
        ok: string;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.recomputeMyAccountId();
                return from_candid_variant_n49(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.recomputeMyAccountId();
            return from_candid_variant_n49(this._uploadFile, this._downloadFile, result);
        }
    }
    async recordIcpSend(arg0: string, arg1: bigint, arg2: bigint): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.recordIcpSend(arg0, arg1, arg2);
                return from_candid_variant_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.recordIcpSend(arg0, arg1, arg2);
            return from_candid_variant_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async recordPaymentTransaction(arg0: Principal, arg1: bigint, arg2: bigint, arg3: string, arg4: string | null): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.recordPaymentTransaction(arg0, arg1, arg2, arg3, to_candid_opt_n50(this._uploadFile, this._downloadFile, arg4));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.recordPaymentTransaction(arg0, arg1, arg2, arg3, to_candid_opt_n50(this._uploadFile, this._downloadFile, arg4));
            return result;
        }
    }
    async recordTokenTransaction(arg0: Principal | null, arg1: Principal | null, arg2: bigint, arg3: string, arg4: string | null, arg5: string, arg6: string | null): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.recordTokenTransaction(to_candid_opt_n51(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n51(this._uploadFile, this._downloadFile, arg1), arg2, arg3, to_candid_opt_n50(this._uploadFile, this._downloadFile, arg4), arg5, to_candid_opt_n50(this._uploadFile, this._downloadFile, arg6));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.recordTokenTransaction(to_candid_opt_n51(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n51(this._uploadFile, this._downloadFile, arg1), arg2, arg3, to_candid_opt_n50(this._uploadFile, this._downloadFile, arg4), arg5, to_candid_opt_n50(this._uploadFile, this._downloadFile, arg6));
            return result;
        }
    }
    async registerFileReference(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.registerFileReference(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerFileReference(arg0, arg1);
            return result;
        }
    }
    async requestToJoinTeam(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.requestToJoinTeam(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.requestToJoinTeam(arg0);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n52(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n52(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async saveGame(arg0: Array<Player>, arg1: Array<Array<Frame>>, arg2: Array<bigint>): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.saveGame(arg0, to_candid_vec_n54(this._uploadFile, this._downloadFile, arg1), arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveGame(arg0, to_candid_vec_n54(this._uploadFile, this._downloadFile, arg1), arg2);
            return result;
        }
    }
    async sendMessage(arg0: string, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.sendMessage(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.sendMessage(arg0, arg1);
            return result;
        }
    }
    async sendStkTokens(arg0: string, arg1: bigint): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.sendStkTokens(arg0, arg1);
                return from_candid_variant_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.sendStkTokens(arg0, arg1);
            return from_candid_variant_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async setAdminIcpWallet(arg0: string): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.setAdminIcpWallet(arg0);
                return from_candid_variant_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setAdminIcpWallet(arg0);
            return from_candid_variant_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async setAdminTreasuryAccount(arg0: string): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.setAdminTreasuryAccount(arg0);
                return from_candid_variant_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setAdminTreasuryAccount(arg0);
            return from_candid_variant_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async setLedgerPrincipal(arg0: Principal): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.setLedgerPrincipal(arg0);
                return from_candid_variant_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setLedgerPrincipal(arg0);
            return from_candid_variant_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async transferFromPoolToUser(arg0: string, arg1: string, arg2: bigint): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.transferFromPoolToUser(arg0, arg1, arg2);
                return from_candid_variant_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.transferFromPoolToUser(arg0, arg1, arg2);
            return from_candid_variant_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async transferTokensBetweenPools(arg0: string, arg1: string, arg2: bigint): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.transferTokensBetweenPools(arg0, arg1, arg2);
                return from_candid_variant_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.transferTokensBetweenPools(arg0, arg1, arg2);
            return from_candid_variant_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async transform(arg0: TransformationInput): Promise<TransformationOutput> {
        if (this.processError) {
            try {
                const result = await this.actor.transform(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.transform(arg0);
            return result;
        }
    }
    async updateCallerAchievements(arg0: Array<string>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateCallerAchievements(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateCallerAchievements(arg0);
            return result;
        }
    }
    async updateCallerProfilePicture(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateCallerProfilePicture(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateCallerProfilePicture(arg0);
            return result;
        }
    }
    async updateCallerUserProfileStats(arg0: bigint, arg1: bigint, arg2: bigint, arg3: bigint, arg4: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateCallerUserProfileStats(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateCallerUserProfileStats(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async updatePlayerStats(arg0: string, arg1: bigint, arg2: bigint, arg3: bigint, arg4: bigint, arg5: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updatePlayerStats(arg0, arg1, arg2, arg3, arg4, arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updatePlayerStats(arg0, arg1, arg2, arg3, arg4, arg5);
            return result;
        }
    }
    async updatePriceFeed(arg0: string, arg1: bigint, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updatePriceFeed(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updatePriceFeed(arg0, arg1, arg2);
            return result;
        }
    }
    async updateTeamStats(arg0: bigint, arg1: bigint, arg2: bigint, arg3: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateTeamStats(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateTeamStats(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async updateTokenPool(arg0: string, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateTokenPool(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateTokenPool(arg0, arg1);
            return result;
        }
    }
    async updateTotalSupply(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateTotalSupply(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateTotalSupply(arg0);
            return result;
        }
    }
    async updateUserBalance(arg0: Principal, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateUserBalance(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateUserBalance(arg0, arg1);
            return result;
        }
    }
    async verifyIcpPayment(arg0: string): Promise<{
        __kind__: "ok";
        ok: bigint;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.verifyIcpPayment(arg0);
                return from_candid_variant_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.verifyIcpPayment(arg0);
            return from_candid_variant_n29(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_Frame_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Frame): Frame {
    return from_candid_record_n25(_uploadFile, _downloadFile, value);
}
function from_candid_Game_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Game): Game {
    return from_candid_record_n21(_uploadFile, _downloadFile, value);
}
function from_candid_PaymentTransaction_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PaymentTransaction): PaymentTransaction {
    return from_candid_record_n41(_uploadFile, _downloadFile, value);
}
function from_candid_TokenTransaction_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TokenTransaction): TokenTransaction {
    return from_candid_record_n16(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n28(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n32(_uploadFile, _downloadFile, value);
}
function from_candid_Wallet_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Wallet): Wallet {
    return from_candid_record_n35(_uploadFile, _downloadFile, value);
}
function from_candid__ImmutableObjectStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __ImmutableObjectStorageRefillResult): _ImmutableObjectStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [Principal]): Principal | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n27(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Wallet]): Wallet | null {
    return value.length === 0 ? null : from_candid_Wallet_n34(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_FileReference]): FileReference | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Game]): Game | null {
    return value.length === 0 ? null : from_candid_Game_n20(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_PaymentTransaction]): PaymentTransaction | null {
    return value.length === 0 ? null : from_candid_PaymentTransaction_n40(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Player]): Player | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_PriceFeed]): PriceFeed | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Team]): Team | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_TokenPool]): TokenPool | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_TokenTransaction]): TokenTransaction | null {
    return value.length === 0 ? null : from_candid_TokenTransaction_n15(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    to: [] | [Principal];
    status: string;
    transactionType: string;
    from: [] | [Principal];
    pool: [] | [string];
    reference: [] | [string];
    timestamp: bigint;
    amount: bigint;
    ledgerHeight: [] | [bigint];
}): {
    id: bigint;
    to?: Principal;
    status: string;
    transactionType: string;
    from?: Principal;
    pool?: string;
    reference?: string;
    timestamp: bigint;
    amount: bigint;
    ledgerHeight?: bigint;
} {
    return {
        id: value.id,
        to: record_opt_to_undefined(from_candid_opt_n17(_uploadFile, _downloadFile, value.to)),
        status: value.status,
        transactionType: value.transactionType,
        from: record_opt_to_undefined(from_candid_opt_n17(_uploadFile, _downloadFile, value.from)),
        pool: record_opt_to_undefined(from_candid_opt_n18(_uploadFile, _downloadFile, value.pool)),
        reference: record_opt_to_undefined(from_candid_opt_n18(_uploadFile, _downloadFile, value.reference)),
        timestamp: value.timestamp,
        amount: value.amount,
        ledgerHeight: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.ledgerHeight))
    };
}
function from_candid_record_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    totalScores: Array<bigint>;
    owner: [] | [Principal];
    players: Array<_Player>;
    timestamp: bigint;
    frames: Array<Array<_Frame>>;
}): {
    id: bigint;
    totalScores: Array<bigint>;
    owner?: Principal;
    players: Array<Player>;
    timestamp: bigint;
    frames: Array<Array<Frame>>;
} {
    return {
        id: value.id,
        totalScores: value.totalScores,
        owner: record_opt_to_undefined(from_candid_opt_n17(_uploadFile, _downloadFile, value.owner)),
        players: value.players,
        timestamp: value.timestamp,
        frames: from_candid_vec_n22(_uploadFile, _downloadFile, value.frames)
    };
}
function from_candid_record_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    score: bigint;
    roll1: bigint;
    roll2: bigint;
    roll3: [] | [bigint];
}): {
    score: bigint;
    roll1: bigint;
    roll2: bigint;
    roll3?: bigint;
} {
    return {
        score: value.score,
        roll1: value.roll1,
        roll2: value.roll2,
        roll3: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.roll3))
    };
}
function from_candid_record_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    principal: Principal;
    displayName: string;
    gamesPlayed: bigint;
    highestScore: bigint;
    totalSpares: bigint;
    achievements: Array<string>;
    games: Array<bigint>;
    totalStrikes: bigint;
    totalPoints: bigint;
    profilePicture: [] | [string];
    averageScore: bigint;
}): {
    principal: Principal;
    displayName: string;
    gamesPlayed: bigint;
    highestScore: bigint;
    totalSpares: bigint;
    achievements: Array<string>;
    games: Array<bigint>;
    totalStrikes: bigint;
    totalPoints: bigint;
    profilePicture?: string;
    averageScore: bigint;
} {
    return {
        principal: value.principal,
        displayName: value.displayName,
        gamesPlayed: value.gamesPlayed,
        highestScore: value.highestScore,
        totalSpares: value.totalSpares,
        achievements: value.achievements,
        games: value.games,
        totalStrikes: value.totalStrikes,
        totalPoints: value.totalPoints,
        profilePicture: record_opt_to_undefined(from_candid_opt_n18(_uploadFile, _downloadFile, value.profilePicture)),
        averageScore: value.averageScore
    };
}
function from_candid_record_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    stkPrincipalId: string;
    icpTransactions: Array<_TokenTransaction>;
    icpAccountId: string;
    stkBalance: bigint;
    stkTransactions: Array<_TokenTransaction>;
}): {
    stkPrincipalId: string;
    icpTransactions: Array<TokenTransaction>;
    icpAccountId: string;
    stkBalance: bigint;
    stkTransactions: Array<TokenTransaction>;
} {
    return {
        stkPrincipalId: value.stkPrincipalId,
        icpTransactions: from_candid_vec_n14(_uploadFile, _downloadFile, value.icpTransactions),
        icpAccountId: value.icpAccountId,
        stkBalance: value.stkBalance,
        stkTransactions: from_candid_vec_n14(_uploadFile, _downloadFile, value.stkTransactions)
    };
}
function from_candid_record_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: string;
    stkAmount: bigint;
    user: Principal;
    reference: [] | [string];
    exchangeRate: bigint;
    timestamp: bigint;
    icpAmount: bigint;
}): {
    id: bigint;
    status: string;
    stkAmount: bigint;
    user: Principal;
    reference?: string;
    exchangeRate: bigint;
    timestamp: bigint;
    icpAmount: bigint;
} {
    return {
        id: value.id,
        status: value.status,
        stkAmount: value.stkAmount,
        user: value.user,
        reference: record_opt_to_undefined(from_candid_opt_n18(_uploadFile, _downloadFile, value.reference)),
        exchangeRate: value.exchangeRate,
        timestamp: value.timestamp,
        icpAmount: value.icpAmount
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_variant_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: null;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: Array<_TokenTransaction>;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: Array<TokenTransaction>;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_vec_n14(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: bigint;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: bigint;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: Principal;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: Principal;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: Array<_TokenPool>;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: Array<TokenPool>;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: string;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: string;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_vec_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_TokenTransaction>): Array<TokenTransaction> {
    return value.map((x)=>from_candid_TokenTransaction_n15(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Game>): Array<Game> {
    return value.map((x)=>from_candid_Game_n20(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<Array<_Frame>>): Array<Array<Frame>> {
    return value.map((x)=>from_candid_vec_n23(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Frame>): Array<Frame> {
    return value.map((x)=>from_candid_Frame_n24(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_UserProfile>): Array<UserProfile> {
    return value.map((x)=>from_candid_UserProfile_n27(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_PaymentTransaction>): Array<PaymentTransaction> {
    return value.map((x)=>from_candid_PaymentTransaction_n40(_uploadFile, _downloadFile, x));
}
function to_candid_Frame_n56(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Frame): _Frame {
    return to_candid_record_n57(_uploadFile, _downloadFile, value);
}
function to_candid_TokenTransaction_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TokenTransaction): _TokenTransaction {
    return to_candid_record_n9(_uploadFile, _downloadFile, value);
}
function to_candid_UserProfile_n52(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): _UserProfile {
    return to_candid_record_n53(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n12(_uploadFile, _downloadFile, value);
}
function to_candid__ImmutableObjectStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ImmutableObjectStorageRefillInformation): __ImmutableObjectStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ImmutableObjectStorageRefillInformation | null): [] | [__ImmutableObjectStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__ImmutableObjectStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_opt_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Principal | null): [] | [Principal] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_record_n53(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    principal: Principal;
    displayName: string;
    gamesPlayed: bigint;
    highestScore: bigint;
    totalSpares: bigint;
    achievements: Array<string>;
    games: Array<bigint>;
    totalStrikes: bigint;
    totalPoints: bigint;
    profilePicture?: string;
    averageScore: bigint;
}): {
    principal: Principal;
    displayName: string;
    gamesPlayed: bigint;
    highestScore: bigint;
    totalSpares: bigint;
    achievements: Array<string>;
    games: Array<bigint>;
    totalStrikes: bigint;
    totalPoints: bigint;
    profilePicture: [] | [string];
    averageScore: bigint;
} {
    return {
        principal: value.principal,
        displayName: value.displayName,
        gamesPlayed: value.gamesPlayed,
        highestScore: value.highestScore,
        totalSpares: value.totalSpares,
        achievements: value.achievements,
        games: value.games,
        totalStrikes: value.totalStrikes,
        totalPoints: value.totalPoints,
        profilePicture: value.profilePicture ? candid_some(value.profilePicture) : candid_none(),
        averageScore: value.averageScore
    };
}
function to_candid_record_n57(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    score: bigint;
    roll1: bigint;
    roll2: bigint;
    roll3?: bigint;
}): {
    score: bigint;
    roll1: bigint;
    roll2: bigint;
    roll3: [] | [bigint];
} {
    return {
        score: value.score,
        roll1: value.roll1,
        roll2: value.roll2,
        roll3: value.roll3 ? candid_some(value.roll3) : candid_none()
    };
}
function to_candid_record_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    to?: Principal;
    status: string;
    transactionType: string;
    from?: Principal;
    pool?: string;
    reference?: string;
    timestamp: bigint;
    amount: bigint;
    ledgerHeight?: bigint;
}): {
    id: bigint;
    to: [] | [Principal];
    status: string;
    transactionType: string;
    from: [] | [Principal];
    pool: [] | [string];
    reference: [] | [string];
    timestamp: bigint;
    amount: bigint;
    ledgerHeight: [] | [bigint];
} {
    return {
        id: value.id,
        to: value.to ? candid_some(value.to) : candid_none(),
        status: value.status,
        transactionType: value.transactionType,
        from: value.from ? candid_some(value.from) : candid_none(),
        pool: value.pool ? candid_some(value.pool) : candid_none(),
        reference: value.reference ? candid_some(value.reference) : candid_none(),
        timestamp: value.timestamp,
        amount: value.amount,
        ledgerHeight: value.ledgerHeight ? candid_some(value.ledgerHeight) : candid_none()
    };
}
function to_candid_variant_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_vec_n54(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<Array<Frame>>): Array<Array<_Frame>> {
    return value.map((x)=>to_candid_vec_n55(_uploadFile, _downloadFile, x));
}
function to_candid_vec_n55(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<Frame>): Array<_Frame> {
    return value.map((x)=>to_candid_Frame_n56(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
